name=DSN_Esp32C3_St7789
version=0.9.0
author=Derda
maintainer=Dsn Industries
sentence=A custom TFT driver for ESP32-C3 and ST7789.
paragraph=Provides an full control of ST7789 Driver.
category=Display
url=https://github.com/derdacavga/DSN-esp32c3-st7789
architectures=*